name: PartyChat
author: KSIO1329
main: me.ksio.partychat.Main
version: 1.0.0
api-version: 1.14
commands:
  party:
    aliases: [pc]
    description: It gives you a look at ALL of the custom enchantments!
    usage: wtf
